inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7
  TargetRailsVersion: 6.0
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'lib/tasks/auto_annotate_models.rake'

Rails:
  Enabled: true

### rubocop setting
Layout/IndentationWidth: #一時的に設定
  Exclude:
    - app/controllers/searches_controller.rb

Style/AsciiComments:
  Enabled: false

### rubocop-rails setting
Metrics/BlockLength:
  Exclude:
    - Gemfile
    - spec/**/*

### rubocop-rspec setting
RSpec/ImplicitSubject:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/NotToNot:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Max: 8

RSpec/NestedGroups: # 一時的に調整（デフォルトは3）
  Max: 6

RSpec/PredicateMatcher:
  Exclude:
    - spec/models/user_spec.rb

RSpec/EmptyExampleGroup: # 一時的に調整（最終的に不要なら消去）
  Exclude:
    - spec/models/comment_spec.rb
    - spec/models/like_spec.rb
    - spec/requests/account_activations_request_spec.rb
    - spec/requests/comments_request_spec.rb
    - spec/requests/likes_request_spec.rb
    - spec/requests/searches_request_spec.rb
    - spec/requests/static_pages_request_spec.rb

Rails/SkipsModelValidations:
  Exclude:
    - app/controllers/password_resets_controller.rb
    - app/models/user.rb
    - spec/system/password_resets_spec.rb

# テストパフォーマンス向上のため
FactoryBot/FactoryClassName:
  Enabled: true

### 一時的に設定（後から消す）
RSpec/InstanceVariable:
  Enabled: false

# Rails/SkipsModelValidations:
#   Enabled: false

RSpec/AnyInstance:
  Enabled: false

# Rails/UniqueValidationWithoutIndex:
#   Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false
