version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/rails/Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/monoge:delegated
    depends_on:
      - db
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    env_file:
      - ./environments/common.env
    ports:
      - 80:80     # 443:443
    depends_on:
      - app
  db:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    ports:
      - 3306:3306
    env_file:
      - ./environments/db.env
    volumes:
      - db-data:/var/lib/mysql:delegated
    security_opt:
      - seccomp:unconfined
  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
volumes:
  db-data:
