version: ‘3’
services:
  db:
    build: docker/mysql
    env_file:
      - ./environments/common.env
      - ./environments/db.env
    volumes:
      - db-data:/var/lib/mysql
  app:
    build: docker/rails
    env_file:
      - ./environments/common.env
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - ./app:/app
    depends_on:
      - db
  web:
    build: docker/nginx
    env_file:
      - ./environments/common.env
    volumes:
      - ./app:/app
      - log-data:/var/log/nginx/
      - cert-data:/etc/nginx/cert/
    ports:
      - 80:80     # 443:443
    depends_on:
      - app
volumes:
  db-data:
  log-data:
  cert-data:
