version: '3'
services:
  db:
    build: docker/mysql
    env_file:
      - ./environments/common.env
      - ./environments/db.env
    volumes:
      - db-data:/var/lib/mysql
    # security_optの追加
  app:
    build: docker/rails
    env_file:
      - ./environments/common.env
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/app
    depends_on:
      - db
  web:
    build: docker/nginx
    env_file:
      - ./environments/common.env
    volumes:
      - .:/app
      - log-data:/var/log/nginx/
      - cert-data:/etc/nginx/cert/
    ports:
      - 80:80     # 443:443
    depends_on:
      - app
  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
volumes:
  db-data:
  log-data:
  cert-data:

# CircleCIの設定も行う
