version: 2
services:
  monoge-rails:
    image: 486601415720.dkr.ecr.ap-northeast-1.amazonaws.com/monoge-rails
    command: ash -c "bundle exec rails db:migrate && bundle exec rails assets:precompile && bundle exec puma -C config/puma.rb"
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: dd35c9a74609881e02f0b940ec585cc2
      DB_DATABASE: monoge_db_prod
      DB_USERNAME: monoge_admin
      DB_PASSWORD: monogepass
      DB_HOST: monoge-db.czyhogiciodt.ap-northeast-1.rds.amazonaws.com
      TZ: Asia/Tokyo
    working_dir: /monoge
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-1
        awslogs-group: monoge/monoge-rails
        awslogs-stream-prefix: monoge
  monoge-nginx:
    image: 486601415720.dkr.ecr.ap-northeast-1.amazonaws.com/monoge-nginx
    ports:
      - 80:80
    links:
      - monoge-rails
    # version2のみ
    volumes_from:
      - monoge-rails
    working_dir: /monoge
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-1
        awslogs-group: monoge/monoge-nginx
        awslogs-stream-prefix: monoge
# sockets /monoge/tmp/socketsをボリュームとしてマウント
# public /monoge/publicをボリュームとしてマウント
